apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-api-deployment
  namespace: microservice-app
  labels:
    app: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-api-pod
  template:
    metadata:
      labels:
        app: js-api-pod
    spec:
      containers:
        - name: js-api-container
          image: josua16/microservice:js-api-1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: docker-creds