apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  namespace: microservice-app
  labels:
    app: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api-pod
  template:
    metadata:
      labels:
        app: python-api-pod
    spec:
      containers:
        - name: python-api-container
          image: josua16/microservice:python-api-1.0
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: docker-creds