apiVersion: v1
kind: Service
metadata:
  name: js-api-service
  namespace: microservice-app
  labels:
    app: microservices
spec:
  selector:
    app: js-api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32007
  type: NodePort      
