  apiVersion: v1
  kind: Service
  metadata:
    name: js-web-service
    namespace: microservice-app
    labels:
      app: microservices
  spec:
    selector:
      app: js-web-pod
    ports:
      - protocol: TCP
        port: 80
        targetPort: 3002
        nodePort: 32005  
    type: NodePort      
