apiVersion: v1
kind: Service
metadata:
  name: python-api-service
  namespace: microservice-app
  labels:
    app: microservices
spec:
  selector:
    app: python-api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 32006  
  type: NodePort      
